### ISSUE TITLE
Is getUserRole() necessary?

### ISSUE THREAD

**Issue by MidnightDesign** [zendframework/zend-expressive-authentication#1]
Why does the `UserInterface` need a `getUserRole()` method? What if my authorization system doesn't use roles?

**Comment by pdrosos** [comment]
In addition to that question I would like to ask why user must have only one role and what to do if user has multiple roles?

**Comment by ezimuel** [comment]
@pdrosos I added the support of multiple roles with PR #4. @MidnightDesign if a user does not have a role, the new `getUserRoles()` can return `null`.

**Comment by pdrosos** [comment]
@ezimuel great, thanks! Will it be merged soon?
Anything I can help with so https://github.com/zendframework/zend-expressive-authorization supports multiple roles too?

@weierophinney I was also wondering if the 2 packages `zend-expressive-authentication` and `zend-expressive-authorization` will be finished and production ready soon, along with their adapters? 
Sorry about the rush, I am just considering to use them in a new project with Zend Expressive and this is one of the main reasons the team may choose to use ZF3 MVC instead, even I personally prefer Zend Expressive and middleware for new projects.

**Comment by weierophinney** [comment]
@pdrosos We're likely going to wait to mark stable 1.0 versions until PSR-15 is accepted, which, currently, looks like sometime in early January. The reason is so that we can target PSR-15 specifically for components offering middleware, instead of worrying about having components that need to support up to three different variants of the specification.

I'm currently testing zend-expressive-authentication with a few Expressive applications, and it's "just working", which is as good of an endorsement as I can provide. Since these are using stable projects underneath (e.g., league/oauth2-server, league/oauth2-client, PDO, zend-authentication, zend-permissions-acl, zend-permissions-rbac), the main thing is the stability of the middleware itself. The middleware _functionality_ will not change once we pin to PSR-15, only the interfaces it implements and consumes. As such, I'd personally move forward with them, particularly if it's an early-stage project; by the time you're ready to hit stable, we already should be.

**Comment by ezimuel** [comment]
@pdrosos I would like to have more feedbacks on this new feature, before merge it. When merged we can extend the changes to and the authentication adapters like [zend-expressive-authentication-oauth2](https://github.com/zendframework/zend-expressive-authentication-oauth2) and [zend-expressive-authorization](https://github.com/zendframework/zend-expressive-authorization).

**Comment by MidnightDesign** [comment]
@ezimuel Perfect, thanks!
