### ISSUE TITLE
propose to AuthenticationInterface

### ISSUE THREAD

**Issue by sergiors** [zendframework/zend-expressive-authentication#11]
Hi, I'm migrate Silex to Expressive on my work.

I was read the authentication code I think `AuthenticationInterface` could have just the method `public function authenticate(ServerRequestInterface $request) : UserInterface` and throw exception when do not have any match.

I can implementation like this

```php
class AuthenticationMiddleware implements MiddlewareInterface
{
    /**
     * @var AuthenticationInterface
     */
    private $auth;

    public function __construct(AuthenticationInterface $auth)
    {
        $this->auth = $auth;
    }

    /**
     * {@inheritDoc}
     */
    public function process(ServerRequestInterface $request, DelegateInterface $delegate)
    {
        try {
            return $delegate->process($request->withAttribute(UserInterface::class, $this->auth->authenticate($request)));
        } catch (Exception\BadRequestException $e) {
            return new Response('php://temp', StatusCode::STATUS_BAD_REQUEST);
        } catch (Exception\UnauthorizedException $e) {
            return new Response('php://temp', StatusCode::STATUS_UNAUTHORIZED);
        }
    }
}
```

```php
class BearerAuthentication implements AuthenticationInterface
{
    public function authenticate(ServerRequestInterface $request): UserInterface
    {
        if (false === ($header = $request->getHeaderLine('Authorization') ?: false)) {
            throw new BadRequestException;
        }

        if (!preg_match('/Bearer\s(\S+)/', $header, $matches)) {
            throw new BadRequestException;
        }
        
        // ....
        
        throw new UnauthorizedException;
    }
}
```

What do you think?

**Comment by weierophinney** [comment]
Failure to authenticate is not really an _exceptional_ circumstance; it's one that is _expected_. Invalid credentials will likely be provided more often than valid credentials. 

Further, exceptions should be used for exceptional circumstances only, and should not be used for conditional processing. This is why we used a nullable type in this situation: failure to authenticate returns a null, while successful authentication returns a user. From there, we can determine what to do next, and branch execution accordingly.

The reason we provide the `unauthorizedResponse()` method (which should likely be renamed to `unauthenticatedResponse()`) is because different authentication mechanisms need to produce different _response artifacts_. As an example, both the HTTP Basic and OAuth2 adapters need to provide a response with a 401 _status code_ that includes a `WWW-Authenticate` _header_. As these artifacts will vary based on adapter, they should be generated by the adapter.

**Comment by sergiors** [comment]
Thanks for your feedback @weierophinney
